# Generated by Django 4.1.7 on 2023-04-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_curso_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nome_curso',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.CharField(max_length=20),
        ),
    ]
