# Generated by Django 4.1.7 on 2023-04-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_curso_nome_curso_alter_curso_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
