# Generated by Django 4.1.7 on 2023-04-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_alter_aluno_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome_curso',
            field=models.CharField(max_length=50),
        ),
    ]
