# Generated by Django 4.2 on 2023-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=100)),
                ('num_telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('preco', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('P', 'Periféricos'), ('E', 'Eletrônico'), ('H', 'Hardware'), ('C', 'Celulares')], max_length=1)),
            ],
        ),
    ]
