# Generated by Django 4.2 on 2023-04-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('P', 'Periféricos'), ('Eletrônico', 'Eletrônico'), ('H', 'Hardware'), ('C', 'Celulares')], max_length=30),
        ),
    ]
