# Generated by Django 4.2 on 2023-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0002_alter_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Periférico', 'Periféricos'), ('Eletrônico', 'Eletrônicos'), ('Hardware', 'Hardwares'), ('Celular', 'Celulares')], max_length=30),
        ),
    ]
