# Generated by Django 4.2 on 2023-04-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0004_alter_produto_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.CharField(max_length=300)),
                ('data_pedido', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('status', models.CharField(choices=[('R', 'Pedido realizado'), ('P', 'Pedido em preparação'), ('E', 'Saiu para entrega')], max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_loja.cliente')),
                ('produtos', models.ManyToManyField(to='app_loja.produto')),
            ],
        ),
    ]
