# Generated by Django 4.2 on 2023-04-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0005_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.CharField(max_length=20),
        ),
    ]
