# Generated by Django 4.2 on 2023-04-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0006_alter_pedido_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='valor',
        ),
    ]
