# Generated by Django 4.2 on 2023-04-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0007_remove_pedido_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('REALIZADO', 'Pedido realizado'), ('PREPARAÇÃO', 'Pedido em preparação'), ('ENTREGA', 'Saiu para entrega')], max_length=30),
        ),
    ]
